// Reading timestamps are generated by the Flask backend's own system clock
// (see database.py: datetime.utcnow()). If that laptop's clock or timezone
// is wrong, every stored timestamp will be wrong too -- no frontend code can
// fix a bad clock at the source. First thing to check on demo day: the
// laptop's OS date/time/timezone are set to "automatic", not manual.
//
// What CAN be fixed from the browser: if the device you're VIEWING the
// dashboard from (e.g. a phone, over Tailscale) has a drifted clock relative
// to the rest of the world, comparing it against a real internet time source
// once on load lets us correct "now" for anything the frontend computes
// itself -- right now, just the ESP32 connected/disconnected check.

let clockOffsetMs = 0;
let synced = false;

export async function syncClock() {
  try {
    const res = await fetch("https://worldtimeapi.org/api/timezone/Etc/UTC");
    if (!res.ok) throw new Error("time sync request failed");
    const data = await res.json();
    const trueUtcMs = new Date(data.utc_datetime).getTime();
    clockOffsetMs = trueUtcMs - Date.now();
    synced = true;
  } catch (e) {
    // Offline, blocked by a firewall, or the API is down -- fall back to
    // the browser's own clock silently. Nothing else depends on this
    // working, so there's nothing to show the user here.
    clockOffsetMs = 0;
    synced = false;
  }
}

export function correctedNowMs() {
  return Date.now() + clockOffsetMs;
}

export function isClockSynced() {
  return synced;
}

// Python's datetime.isoformat() can emit 6-digit microsecond fractions
// (e.g. "...23.456789Z"), which some browsers' Date parsers reject as
// invalid even though it's a harmless superset of the millisecond format
// they expect. Trim to 3 digits before parsing so old rows in the DB
// (written before this was fixed at the source) still parse correctly.
export function parseTimestamp(ts) {
  if (!ts) return null;
  const normalized = ts.replace(/(\.\d{3})\d*(Z)$/, "$1$2");
  const ms = new Date(normalized).getTime();
  return Number.isNaN(ms) ? null : ms;
}
